# Generated by Django 5.2.17 on 2026-10-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('job_cards', '0001_initial'),
        ('organizations', '0002_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='job_cards.jobcard'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.part'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['organization', 'active', 'name'], name='part_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='part_unique_sku'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='part_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0), ('selling_price__gte', 0)), name='part_prices_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['part', '-created_at'], name='stock_tx_part_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['organization', 'transaction_type', '-created_at'], name='stock_tx_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_tx_non_zero'),
        ),
    ]
