# Generated by Django 5.2.17 on 2026-10-06 12:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocktransaction_line_no'),
        ('organizations', '0002_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='part',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='GST HSN code (4–8 digits)', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]{4,8}$', 'HSN code must be 4–8 digits.')]),
        ),
        migrations.AddField(
            model_name='part',
            name='rack_location',
            field=models.CharField(blank=True, help_text='Where it sits, e.g. Rack B · Shelf 3', max_length=50),
        ),
        migrations.AddField(
            model_name='part',
            name='universal',
            field=models.BooleanField(default=False, help_text='Fits every vehicle (bulbs, generic fluids…)'),
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'part categories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.partcategory'),
        ),
        migrations.CreateModel(
            name='PartFitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('EV', 'Electric vehicle'), ('OTHER', 'Other')], max_length=10)),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='inventory.part')),
            ],
            options={
                'ordering': ('brand', 'model'),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GSTIN.')])),
                ('address', models.CharField(blank=True, max_length=300)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='part',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Who it was bought from (purchases)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.supplier'),
        ),
        migrations.AddConstraint(
            model_name='partcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='part_category_unique_name'),
        ),
        migrations.AddIndex(
            model_name='partfitment',
            index=models.Index(fields=['organization', 'brand', 'model'], name='fitment_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='partfitment',
            constraint=models.CheckConstraint(condition=models.Q(('year_from__isnull', True), ('year_to__isnull', True), ('year_from__lte', models.F('year_to')), _connector='OR'), name='fitment_year_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='supplier_unique_name'),
        ),
    ]
