# Generated by Django 5.2.17 on 2026-10-06 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0002_organization_timezone'),
        ('services', '0002_seed_catalog'),
        ('vehicles', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_number', models.CharField(max_length=20, unique=True)),
                ('booking_date', models.DateField(help_text='Local date at the agency')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('VEHICLE_RECEIVED', 'Vehicle received'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_APPROVAL', 'Waiting for approval'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('NO_SHOW', 'No show')], default='PENDING', max_length=24)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=16)),
                ('source', models.CharField(choices=[('ONLINE', 'Customer app'), ('AGENCY', 'Created by agency')], default='ONLINE', max_length=10)),
                ('customer_notes', models.TextField(blank=True, max_length=2000)),
                ('internal_notes', models.TextField(blank=True, max_length=4000)),
                ('pickup_requested', models.BooleanField(default=False)),
                ('drop_requested', models.BooleanField(default=False)),
                ('pickup_address', models.TextField(blank=True)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vendors.serviceresource')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicles.vehicle')),
                ('vendor_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.vendorservice')),
            ],
            options={
                'ordering': ('-start_datetime',),
            },
        ),
        migrations.CreateModel(
            name='BookingReschedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_start', models.DateTimeField()),
                ('old_end', models.DateTimeField()),
                ('new_start', models.DateTimeField()),
                ('new_end', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='bookings.booking')),
                ('new_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendors.serviceresource')),
                ('old_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vendors.serviceresource')),
                ('rescheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'booking status history',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organization', 'start_datetime'], name='booking_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organization', 'status'], name='booking_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vendor_service', 'start_datetime'], name='booking_vs_start_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['assigned_resource', 'start_datetime'], name='booking_resource_start_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-start_datetime'], name='booking_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle', 'start_datetime'], name='booking_vehicle_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='booking_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['end_datetime'], name='booking_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'ASSIGNED', 'VEHICLE_RECEIVED', 'IN_PROGRESS', 'WAITING_FOR_APPROVAL', 'COMPLETED', 'CANCELLED', 'REJECTED', 'NO_SHOW'])), name='booking_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_price__gte', 0)), name='booking_price_non_negative'),
        ),
    ]
