# Generated by Django 5.2.17 on 2026-10-06 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('BOOKING_CREATED', 'Booking created'), ('BOOKING_CONFIRMED', 'Booking confirmed'), ('BOOKING_REJECTED', 'Booking rejected'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('BOOKING_RESCHEDULED', 'Booking rescheduled'), ('BOOKING_REMINDER', 'Booking reminder'), ('VEHICLE_RECEIVED', 'Vehicle received'), ('SERVICE_STARTED', 'Service started'), ('ADDITIONAL_WORK_REQUESTED', 'Additional work requested'), ('ADDITIONAL_WORK_RESPONDED', 'Additional work responded'), ('SERVICE_COMPLETED', 'Service completed'), ('PAYMENT_RECEIVED', 'Payment received'), ('INVOICE_GENERATED', 'Invoice generated'), ('NEW_BOOKING_FOR_AGENCY', 'New booking (agency)')], max_length=32)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('to_address', models.CharField(blank=True, help_text='E-mail or phone for external channels', max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'channel', '-created_at'], name='notification_inbox_idx'), models.Index(fields=['recipient', 'read_at'], name='notification_unread_idx'), models.Index(fields=['status', 'channel'], name='notification_delivery_idx')],
            },
        ),
    ]
