# Generated by Django 5.2.17 on 2026-10-06 05:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('CLEANING', 'Cleaning & detailing'), ('TYRES_WHEELS', 'Tyres & wheels'), ('ELECTRICAL', 'Electrical & battery'), ('DIAGNOSTICS', 'Diagnostics'), ('ASSISTANCE', 'Assistance'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('supported_vehicle_types', models.JSONField(default=list, help_text='List of VehicleType values.')),
                ('default_duration', models.PositiveSmallIntegerField(help_text='Minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST rate in percent.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', 'name'),
                'indexes': [models.Index(fields=['active', 'category'], name='service_active_category_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='service_price_non_negative'), models.CheckConstraint(condition=models.Q(('tax__gte', 0), ('tax__lte', 100)), name='service_tax_range'), models.CheckConstraint(condition=models.Q(('default_duration__gte', 5)), name='service_duration_min')],
            },
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('custom_duration', models.PositiveSmallIntegerField(blank=True, help_text='Minutes', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Bookings that can run in parallel in one slot.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('required_resource_type', models.CharField(blank=True, choices=[('BAY', 'Service bay'), ('TECHNICIAN', 'Technician'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], help_text='If set, every booking reserves one free resource of this type (e.g. a bay).', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('pickup_available', models.BooleanField(default=False)),
                ('drop_available', models.BooleanField(default=False)),
                ('online_booking_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_offerings', to='services.service')),
            ],
            options={
                'ordering': ('service__name',),
                'indexes': [models.Index(fields=['organization', 'active'], name='vendor_service_org_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'service'), name='vendor_service_unique'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='vendor_service_capacity_min'), models.CheckConstraint(condition=models.Q(('custom_price__isnull', True), ('custom_price__gte', 0), _connector='OR'), name='vendor_service_price_non_negative')],
            },
        ),
    ]
