# Generated by Django 5.2.17 on 2026-10-06 05:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Step between slot starts. Empty = service duration + buffer.', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=0, help_text='Gap kept free after every booking.', validators=[django.core.validators.MaxValueValidator(240)])),
                ('booking_lead_time_minutes', models.PositiveIntegerField(default=60, help_text='Earliest bookable slot from now.', validators=[django.core.validators.MaxValueValidator(10080)])),
                ('max_advance_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('cancellation_cutoff_hours', models.PositiveSmallIntegerField(default=2, help_text='Customers cannot cancel/reschedule closer than this to the start time.', validators=[django.core.validators.MaxValueValidator(168)])),
                ('auto_confirm_bookings', models.BooleanField(default=False)),
                ('additional_work_requires_approval', models.BooleanField(default=True)),
                ('require_online_payment', models.BooleanField(default=False, help_text='Customers pay (mock gateway) when booking.')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'agency settings',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('kind', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('EMERGENCY_CLOSURE', 'Emergency closure')], default='HOLIDAY', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('start_date',),
                'indexes': [models.Index(fields=['organization', 'start_date', 'end_date'], name='holiday_org_range_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='holiday_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='ServiceResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('resource_type', models.CharField(choices=[('BAY', 'Service bay'), ('TECHNICIAN', 'Technician'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('staff', models.ForeignKey(blank=True, help_text='For technicians: the staff member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('resource_type', 'name'),
                'indexes': [models.Index(fields=['organization', 'resource_type', 'active'], name='resource_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='resource_unique_name')],
            },
        ),
        migrations.CreateModel(
            name='SpecialWorkingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('date', 'opens_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='special_day_close_after_open'), models.UniqueConstraint(fields=('organization', 'date', 'opens_at'), name='special_day_unique_start')],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'working hours',
                'ordering': ('weekday', 'opens_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='working_hours_close_after_open'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='working_hours_weekday'), models.UniqueConstraint(fields=('organization', 'weekday', 'opens_at'), name='working_hours_unique_start')],
            },
        ),
    ]
