# Generated by Django 5.2.17 on 2026-10-06 04:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_RESET', 'Password reset'), ('EMAIL_VERIFIED', 'Email verified'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('PERMISSIONS_CHANGED', 'Permissions changed'), ('AGENCY_REGISTERED', 'Agency registered'), ('AGENCY_UPDATED', 'Agency updated'), ('AGENCY_APPROVED', 'Agency approved'), ('AGENCY_REJECTED', 'Agency rejected'), ('AGENCY_SUSPENDED', 'Agency suspended'), ('AGENCY_REACTIVATED', 'Agency reactivated'), ('AGENCY_DEACTIVATED', 'Agency deactivated'), ('BOOKING_CREATED', 'Booking created'), ('BOOKING_UPDATED', 'Booking updated'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('PAYMENT_CHANGED', 'Payment changed'), ('INVOICE_CHANGED', 'Invoice changed'), ('SERVICE_PRICE_CHANGED', 'Service price changed')], max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_org_created_idx'), models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_created_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_object_idx')],
            },
        ),
    ]
