# Generated by Django 5.2.17 on 2026-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_RESET', 'Password reset'), ('EMAIL_VERIFIED', 'Email verified'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('PERMISSIONS_CHANGED', 'Permissions changed'), ('AGENCY_REGISTERED', 'Agency registered'), ('AGENCY_UPDATED', 'Agency updated'), ('AGENCY_APPROVED', 'Agency approved'), ('AGENCY_REJECTED', 'Agency rejected'), ('AGENCY_SUSPENDED', 'Agency suspended'), ('AGENCY_REACTIVATED', 'Agency reactivated'), ('AGENCY_DEACTIVATED', 'Agency deactivated'), ('ROLE_CHANGED', 'Role changed'), ('SCHEDULE_CHANGED', 'Working schedule changed'), ('SETTINGS_CHANGED', 'Settings changed'), ('RESOURCE_CHANGED', 'Resource changed'), ('CUSTOMER_CREATED', 'Customer created'), ('CUSTOMER_UPDATED', 'Customer updated'), ('VEHICLE_CREATED', 'Vehicle created'), ('VEHICLE_UPDATED', 'Vehicle updated'), ('VEHICLE_ARCHIVED', 'Vehicle archived'), ('BOOKING_CREATED', 'Booking created'), ('BOOKING_UPDATED', 'Booking updated'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('PAYMENT_CHANGED', 'Payment changed'), ('INVOICE_CHANGED', 'Invoice changed'), ('SERVICE_PRICE_CHANGED', 'Service price changed')], max_length=64),
        ),
    ]
