# Generated by Django 5.2.17 on 2026-10-06 04:51

import apps.accounts.models
import apps.core.storage
import apps.core.validators
import django.core.validators
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{7,15}$', 'Enter a valid phone number (7-15 digits, optional +).')])),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('AGENCY_ADMIN', 'Agency Admin'), ('AGENCY_MANAGER', 'Agency Manager'), ('AGENCY_STAFF', 'Agency Staff'), ('CUSTOMER', 'Customer')], db_index=True, default='CUSTOMER', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, storage=apps.core.storage.media_storage, upload_to=apps.core.storage.UploadPath('users/photos'), validators=[apps.core.validators.ImageFileValidator(max_height=2048, max_width=2048)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can log into the Django admin site.')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-date_joined',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'), models.CheckConstraint(condition=models.Q(('role__in', ['SUPER_ADMIN', 'AGENCY_ADMIN', 'AGENCY_MANAGER', 'AGENCY_STAFF', 'CUSTOMER'])), name='accounts_user_role_valid')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
