# Generated by Django 5.2.17 on 2026-10-06 05:15

import apps.core.storage
import apps.core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('EV', 'Electric vehicle'), ('OTHER', 'Other')], max_length=10)),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=80)),
                ('variant', models.CharField(blank=True, max_length=80)),
                ('registration_number', models.CharField(max_length=20)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('chassis_number', models.CharField(blank=True, max_length=30)),
                ('engine_number', models.CharField(blank=True, max_length=30)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('LPG', 'LPG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('OTHER', 'Other')], default='PETROL', max_length=10)),
                ('manufacturing_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950)])),
                ('color', models.CharField(blank=True, max_length=40)),
                ('odometer', models.PositiveIntegerField(blank=True, help_text='Kilometres', null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('pollution_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Archived vehicles stay in service history.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'ordering': ('brand', 'model'),
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('RC', 'Registration certificate'), ('INSURANCE', 'Insurance'), ('PUC', 'Pollution certificate'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(storage=apps.core.storage.media_storage, upload_to=apps.core.storage.UploadPath('vehicles/documents'), validators=[apps.core.validators.DocumentFileValidator()])),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicle_registration_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicle_vin_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['customer', 'is_active'], name='vehicle_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'registration_number'), name='vehicle_unique_registration_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('vin', ''), _negated=True)), fields=('customer', 'vin'), name='vehicle_unique_vin_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('vehicle_type__in', ['CAR', 'BIKE', 'SCOOTER', 'EV', 'OTHER'])), name='vehicle_type_valid'),
        ),
    ]
