# Generated by Django 5.2.17 on 2026-10-06 12:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0002_organization_timezone'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('EV', 'Electric vehicle'), ('OTHER', 'Other')], default='SCOOTER', max_length=10)),
                ('brand', models.CharField(max_length=60)),
                ('name', models.CharField(help_text='Model name, e.g. Jupiter 125', max_length=80)),
                ('variant', models.CharField(blank=True, help_text='e.g. Disc, SmartXonnect', max_length=80)),
                ('launch_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('LPG', 'LPG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('OTHER', 'Other')], default='PETROL', max_length=10)),
                ('engine_cc', models.PositiveIntegerField(blank=True, help_text='Engine cc (blank for EVs)', null=True)),
                ('colours', models.CharField(blank=True, help_text='Comma-separated colours', max_length=200)),
                ('ex_showroom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text='Alert when stock falls to this level')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('brand', 'name', 'variant'),
            },
        ),
        migrations.CreateModel(
            name='VehicleSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_name', models.CharField(max_length=150)),
                ('buyer_phone', models.CharField(max_length=16)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_address', models.CharField(blank=True, max_length=300)),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('chassis_number', models.CharField(blank=True, max_length=40)),
                ('engine_number', models.CharField(blank=True, max_length=40)),
                ('registration_number', models.CharField(blank=True, max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_mode', models.CharField(blank=True, help_text='Cash, UPI, Finance…', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=40)),
                ('sold_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_purchases', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_sales', to=settings.AUTH_USER_MODEL)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='vehicles.vehiclemodel')),
            ],
            options={
                'ordering': ('-sold_on', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('organization', 'brand', 'name', 'variant'), name='vehicle_model_unique_per_agency'),
        ),
    ]
