# Generated by Django 5.2.17 on 2026-10-06 05:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{7,15}$', 'Enter a valid phone number (7-15 digits, optional +).')])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True, help_text="Customer's own notes (e.g. preferred contact time).")),
                ('owner_organization', models.ForeignKey(blank=True, help_text='Set for walk-in customers created by an agency (they own the record).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='AgencyCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('BOOKING', 'Online booking'), ('WALK_IN', 'Walk-in / added by agency')], default='BOOKING', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_links', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=4000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_notes', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['full_name'], name='customer_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='agencycustomer',
            constraint=models.UniqueConstraint(fields=('organization', 'customer'), name='agency_customer_unique'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['organization', 'customer', '-created_at'], name='customer_note_idx'),
        ),
    ]
