# Generated by Django 5.2.17 on 2026-10-06 05:37

import apps.core.storage
import apps.core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organizations', '0002_organization_timezone'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_card_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INSPECTION', 'Inspection'), ('WORK_IN_PROGRESS', 'Work in progress'), ('WAITING_APPROVAL', 'Waiting approval'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('inspection_notes', models.TextField(blank=True)),
                ('vehicle_condition', models.TextField(blank=True)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_level', models.CharField(blank=True, choices=[('EMPTY', 'Empty'), ('QUARTER', '1/4'), ('HALF', '1/2'), ('THREE_QUARTER', '3/4'), ('FULL', 'Full')], max_length=16)),
                ('existing_damage', models.TextField(blank=True)),
                ('customer_requests', models.TextField(blank=True)),
                ('technician_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_card', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('EXTERIOR', 'Exterior'), ('INTERIOR', 'Interior'), ('TYRES', 'Tyres'), ('BRAKES', 'Brakes'), ('LIGHTS', 'Lights'), ('ENGINE', 'Engine'), ('BATTERY', 'Battery'), ('AC', 'AC'), ('FLUIDS', 'Fluids'), ('OTHER', 'Other')], max_length=12)),
                ('stage', models.CharField(choices=[('BEFORE', 'Before service'), ('AFTER', 'After service')], default='BEFORE', max_length=8)),
                ('result', models.CharField(choices=[('OK', 'OK'), ('ATTENTION', 'Needs attention'), ('REPLACE', 'Replace'), ('NOT_CHECKED', 'Not checked')], default='NOT_CHECKED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='job_cards.jobcard')),
            ],
            options={
                'ordering': ('stage', 'area'),
            },
        ),
        migrations.CreateModel(
            name='AdditionalWorkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=2000)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('customer_response', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approved', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_work', to='job_cards.jobcard')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobCardPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='job_cards.jobcard')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_usages', to='inventory.part')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobCardPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('BEFORE', 'Before service'), ('AFTER', 'After service'), ('OTHER', 'Other')], default='BEFORE', max_length=8)),
                ('image', models.ImageField(storage=apps.core.storage.media_storage, upload_to=apps.core.storage.UploadPath('job_cards/photos'), validators=[apps.core.validators.ImageFileValidator(max_height=8000, max_width=8000)])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='job_cards.jobcard')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('stage', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['organization', 'status'], name='job_card_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['vehicle', '-created_at'], name='job_card_vehicle_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionitem',
            constraint=models.UniqueConstraint(fields=('job_card', 'area', 'stage'), name='inspection_unique_area'),
        ),
        migrations.AddConstraint(
            model_name='additionalworkrequest',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0)), name='additional_work_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='jobcardpart',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__lte', models.F('quantity'))), name='job_part_return_lte_used'),
        ),
    ]
