# Generated by Django 5.2.17 on 2026-10-06 05:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('organizations', '0002_organization_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('method', models.CharField(choices=[('MOCK', 'Mock gateway'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('UPI', 'UPI')], default='MOCK', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], default='PENDING', max_length=20)),
                ('gateway', models.CharField(blank=True, max_length=40)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reference', models.CharField(blank=True, help_text='Cheque / UTR / receipt number', max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='payment_org_status_idx'), models.Index(fields=['booking'], name='payment_booking_idx'), models.Index(fields=['invoice'], name='payment_invoice_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'), models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0), ('refunded_amount__lte', models.F('amount'))), name='payment_refund_within_amount')],
            },
        ),
    ]
