# Generated by Django 5.2.17 on 2026-10-06 04:51

import apps.core.storage
import apps.core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, storage=apps.core.storage.media_storage, upload_to=apps.core.storage.UploadPath('organizations/logos'), validators=[apps.core.validators.ImageFileValidator(max_height=2048, max_width=2048)])),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('gst_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GSTIN.')])),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{7,15}$', 'Enter a valid phone number (7-15 digits, optional +).')])),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 \\-]{3,10}$', 'Enter a valid postal code.')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('status_reason', models.TextField(blank=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['status'], name='org_status_idx'), models.Index(fields=['city', 'status'], name='org_city_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'REJECTED'])), name='org_status_valid'), models.CheckConstraint(condition=models.Q(('verification_status__in', ['UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED'])), name='org_verification_status_valid'), models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='org_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='org_longitude_range')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['organization', 'is_active'], name='membership_org_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='membership_user_org_unique'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='membership_one_active_per_user')],
            },
        ),
    ]
