# Generated by Django 5.2.17 on 2026-10-06 05:07

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='IANA zone used to interpret working hours and slots.', max_length=64, validators=[apps.organizations.models.validate_timezone]),
        ),
    ]
